"""Shared physics label maps for SLAT packages."""

from .constants import (
    ELL_SPEC_MAP,
    ENERGY_TYPE_LATEX_MAP,
    ENERGY_TYPES,
    IRREP_LATEX_MAP,
    NI_PAIR_ENERGY_TYPES,
    PARTICLE_LATEX_MAP,
    QC_MATRIX_LATEX_MAP,
    QC_TYPE_LATEX_MAP,
    SHIFT_ENERGY_TYPES,
    VERBOSITY_MAP,
    _half_int_latex,
    create_spectro_bidict,
    get_all_irrep_latex_mappings,
    get_all_particle_latex_mappings,
    get_all_qcmatrix_latex_mappings,
    get_all_qctype_latex_mappings,
    get_energy_type_latex_str,
    get_irrep_latex_str,
    get_particle_latex_str,
    get_qc_matrix_latex_str,
    get_qc_type_latex_str,
    get_spectro_latex_str,
    get_spectro_str,
    get_twoJ_L_twoS_from_spectro,
    wrap_str_in_determinant,
)

__all__ = [
    "ENERGY_TYPE_LATEX_MAP",
    "ENERGY_TYPES",
    "SHIFT_ENERGY_TYPES",
    "NI_PAIR_ENERGY_TYPES",
    "VERBOSITY_MAP",
    "PARTICLE_LATEX_MAP",
    "IRREP_LATEX_MAP",
    "QC_MATRIX_LATEX_MAP",
    "QC_TYPE_LATEX_MAP",
    "ELL_SPEC_MAP",
    "create_spectro_bidict",
    "_half_int_latex",
    "get_energy_type_latex_str",
    "get_particle_latex_str",
    "get_all_particle_latex_mappings",
    "get_irrep_latex_str",
    "get_all_irrep_latex_mappings",
    "get_spectro_str",
    "get_twoJ_L_twoS_from_spectro",
    "get_spectro_latex_str",
    "get_qc_matrix_latex_str",
    "get_all_qcmatrix_latex_mappings",
    "get_qc_type_latex_str",
    "get_all_qctype_latex_mappings",
    "wrap_str_in_determinant",
]
