"""
Type stub file for SpectraCollection to enable IDE autocomplete.
"""

from typing import Dict, List, Callable, Union
from .sampling import SigmondSampling, ObservableInfo, SamplingInfo
import numpy as np

class SpectraCollection:
    """A queryable collection of spectra with fast filtering and iteration."""

    def __init__(self, data: List[SigmondSampling], return_type: str = 'dict') -> None: ...

    # Return type configuration
    @property
    def return_type(self) -> str: ...
    @return_type.setter
    def return_type(self, value: str) -> None: ...

    # Core collection methods
    def filter(self, **kwargs) -> SpectraCollection: ...
    def find(self, predicate: Callable[[ObservableInfo], bool]) -> SpectraCollection: ...
    def sort(self, by: Union[str, List[str]] = None, key: Callable[[SigmondSampling], any] = None, reverse: bool = False) -> SpectraCollection: ...
    def to_dict(self) -> Dict[ObservableInfo, SigmondSampling]: ...
    def to_dataframe(self) -> "pd.DataFrame": ...
    def apply(self, func_or_method: Union[str, Callable], *args, **kwargs) -> Union[SpectraCollection, Dict, List]: ...

    # Collection protocol
    def __iter__(self) -> iter: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[int, slice]) -> Union[SigmondSampling, SpectraCollection]: ...
    def __contains__(self, item: Union[SigmondSampling, ObservableInfo]) -> bool: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

    # Properties from SigmondSampling (return dict or list based on return_type)
    @property
    def mean(self) -> Union[Dict[ObservableInfo, float], List[float]]: ...
    @property
    def error(self) -> Union[Dict[ObservableInfo, float], List[float]]: ...
    @property
    def full_sample_value(self) -> Union[Dict[ObservableInfo, float], List[float]]: ...
    @property
    def data(self) -> Union[Dict[ObservableInfo, np.ndarray], List[np.ndarray]]: ...
    @property
    def observable_info(self) -> Union[Dict[ObservableInfo, ObservableInfo], List[ObservableInfo]]: ...
    @property
    def sampling_info(self) -> Union[Dict[ObservableInfo, "SamplingInfo"], List["SamplingInfo"]]: ...
    @property
    def is_complex(self) -> Union[Dict[ObservableInfo, bool], List[bool]]: ...

    # Methods from SigmondSampling (return SpectraCollection or dict/list based on return_type)
    def rescale(self, factor: float) -> SpectraCollection: ...
    def pdg_format(self, use_ascii: bool = False) -> Union[Dict[ObservableInfo, str], List[str]]: ...
    def as_energy_level(self, force_type: str = "auto", **manual_overrides) -> SpectraCollection: ...

    # Arithmetic operations (return SpectraCollection)
    def __add__(self, other: Union[SigmondSampling, float]) -> SpectraCollection: ...
    def __sub__(self, other: Union[SigmondSampling, float]) -> SpectraCollection: ...
    def __mul__(self, other: float) -> SpectraCollection: ...
    def __truediv__(self, other: float) -> SpectraCollection: ...
    def __radd__(self, other: Union[SigmondSampling, float]) -> SpectraCollection: ...
    def __rsub__(self, other: Union[SigmondSampling, float]) -> SpectraCollection: ...
    def __rmul__(self, other: float) -> SpectraCollection: ...
    def __neg__(self) -> SpectraCollection: ...
